name: docker-openmetadata-server release app

on:
  workflow_dispatch:
    inputs:
      docker_release_tag:
        description: "Server Docker Image Tag"
        required: true
      push_latest_tag_to_release:
        description: "Do you want to update docker image latest tag as well?"
        type: boolean

jobs:
  maven-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Install antlr cli
        run: |
          sudo make install_antlr_cli

      - name: Setup jq
        run: |
          sudo apt-get update
          sudo apt-get install jq

      - name: Build OpenMetadata Server Application
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mvn -DskipTests clean package




      - name: Upload OpenMetadata application
        uses: actions/upload-artifact@v4
        with:
          name: openmetadata-dist
          path: openmetadata-dist/target/*.tar.gz



  push_to_acr:
    runs-on: ubuntu-latest
    needs: [maven-build]
    steps:
      - name: Check out the Repo
        uses: actions/checkout@v4

      - name: Download OpenMetadata application
        uses: actions/download-artifact@v4
        with:
          name: openmetadata-dist
          path: ./openmetadata-dist

      - name: Set build arguments
        id: build-args
        run: |
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER }}/dataworks-docs:${{ inputs.docker_release_tag }}
            ${{ inputs.push_latest_tag_to_release == 'true' && format('{0}/dataworks-docs:latest', secrets.ACR_LOGIN_SERVER) || '' }}
          file: ./docker/docker-compose-quickstart/Dockerfile
          build-args: |
            RI_VERSION=${{ inputs.docker_release_tag }}
            BUILD_DATE=${{ steps.build-args.outputs.BUILD_DATE }}
            COMMIT_ID=${{ github.sha }}
